services:
  test-db:
    image: postgres:15
    container_name: ticket-db
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - testpgdata:/var/lib/postgresql/data
    networks:
      - testnet
  
  ticket-test:
    build:
      context: ./ticket-backend/services/ticket
      target: builder
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      TEST_DATABASE_URL: postgres://admin:secret@test-db:5432/ticketdb?sslmode=disable
    command: >
      sh -c "
        migrate -path db/migrations -database $$TEST_DATABASE_URL up &&
        go test -v ./...
      "
    networks:
      - testnet

volumes:
  testpgdata:

networks:
  testnet:
