services:
  db:
    image: postgres:15
    container_name: ticket-db
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - halen
      
  ticket-service:
    build:
      context: ./ticket-backend/services/ticket
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      DATABASE_URL: postgres://admin:secret@db:5432/ticketdb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        migrate -path db/migrations -database $$DATABASE_URL up &&
        ./server
      "
    networks:
      - halen

  frontend:
    build:
      context: ./ticket-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8081
    depends_on:
      - ticket-service
    networks:
      - halen

volumes:
  pgdata:

networks:
  halen:
