INSERT INTO tickets (customer_name, email, created_at, status, notes)
VALUES 
  ('Jane Doe', 'jane@example.com', now(), 'open', 'Welcome ticket'),
  ('John Smith', 'john@example.com', now(), 'pending', 'Waiting on user'),
  ('Alice Johnson', 'alice@example.com', now(), 'done', 'Closed after resolution'),
  ('Bob Brown', 'bob@example.com', now(), 'open', 'Initial setup issue'),
  ('Clara Adams', 'clara@example.com', now(), 'pending', 'Escalated to Tier 2'),
  ('Derek Lee', 'derek@example.com', now(), 'done', 'Resolved on call'),
  ('Ella White', 'ella@example.com', now(), 'open', 'Requested password reset'),
  ('Frank Green', 'frank@example.com', now(), 'done', 'Issue resolved automatically'),
  ('Gina Black', 'gina@example.com', now(), 'pending', 'Follow-up required'),
  ('Henry Clark', 'henry@example.com', now(), 'open', 'Email bounce issue'),
  ('Ivy Foster', 'ivy@example.com', now(), 'done', 'Marked as spam'),
  ('Jack Moore', 'jack@example.com', now(), 'pending', 'Investigating logs'),
  ('Karen King', 'karen@example.com', now(), 'open', 'New feature request'),
  ('Liam Scott', 'liam@example.com', now(), 'open', 'Account locked'),
  ('Mia Hill', 'mia@example.com', now(), 'done', 'Duplicate ticket'),
  ('Noah Allen', 'noah@example.com', now(), 'open', 'Subscription issue'),
  ('Olivia Baker', 'olivia@example.com', now(), 'pending', 'Needs review'),
  ('Paul Wright', 'paul@example.com', now(), 'done', 'User confirmed fix'),
  ('Quinn Reed', 'quinn@example.com', now(), 'open', 'Slow performance'),
  ('Ruby Young', 'ruby@example.com', now(), 'open', 'Feature not working'),
  ('Sam Bennett', 'sam@example.com', now(), 'pending', 'Need more info'),
  ('Tina Murphy', 'tina@example.com', now(), 'open', 'UI glitch reported'),
  ('Uma Torres', 'uma@example.com', now(), 'done', 'Refund issued'),
  ('Victor James', 'victor@example.com', now(), 'open', 'Integration help'),
  ('Wendy Lopez', 'wendy@example.com', now(), 'pending', 'Transferred to billing'),
  ('Xander Price', 'xander@example.com', now(), 'done', 'Migration completed'),
  ('Yara Evans', 'yara@example.com', now(), 'open', 'Cannot export data'),
  ('Zane Brooks', 'zane@example.com', now(), 'pending', 'Waiting on dev team'),
  ('Alan Cruz', 'alan@example.com', now(), 'open', 'Question about invoice'),
  ('Bea Stone', 'bea@example.com', now(), 'done', 'Closed via email');
